/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.notificationmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.notificationmgt.model.NotificationConfig;
import org.opencps.notificationmgt.model.NotificationConfigModel;
import org.opencps.notificationmgt.model.NotificationConfigSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the NotificationConfig service. Represents a row in the &quot;opencps_notification_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.notificationmgt.model.NotificationConfigModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationConfigImpl}.
 * </p>
 *
 * @author trungdk
 * @see NotificationConfigImpl
 * @see org.opencps.notificationmgt.model.NotificationConfig
 * @see org.opencps.notificationmgt.model.NotificationConfigModel
 * @generated
 */
@JSON(strict = true)
public class NotificationConfigModelImpl extends BaseModelImpl<NotificationConfig>
	implements NotificationConfigModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification config model instance should use the {@link org.opencps.notificationmgt.model.NotificationConfig} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_notification_config";
	public static final Object[][] TABLE_COLUMNS = {
			{ "notificationConfigId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "eventPattern", Types.VARCHAR },
			{ "notificationURL", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_notification_config (notificationConfigId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,eventPattern VARCHAR(75) null,notificationURL VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table opencps_notification_config";
	public static final String ORDER_BY_JPQL = " ORDER BY notificationConfig.notificationConfigId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_notification_config.notificationConfigId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.notificationmgt.model.NotificationConfig"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.notificationmgt.model.NotificationConfig"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NotificationConfig toModel(NotificationConfigSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NotificationConfig model = new NotificationConfigImpl();

		model.setNotificationConfigId(soapModel.getNotificationConfigId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEventPattern(soapModel.getEventPattern());
		model.setNotificationURL(soapModel.getNotificationURL());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NotificationConfig> toModels(
		NotificationConfigSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NotificationConfig> models = new ArrayList<NotificationConfig>(soapModels.length);

		for (NotificationConfigSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.notificationmgt.model.NotificationConfig"));

	public NotificationConfigModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _notificationConfigId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNotificationConfigId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _notificationConfigId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationConfig.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationConfig.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("notificationConfigId", getNotificationConfigId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("eventPattern", getEventPattern());
		attributes.put("notificationURL", getNotificationURL());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long notificationConfigId = (Long)attributes.get("notificationConfigId");

		if (notificationConfigId != null) {
			setNotificationConfigId(notificationConfigId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String eventPattern = (String)attributes.get("eventPattern");

		if (eventPattern != null) {
			setEventPattern(eventPattern);
		}

		String notificationURL = (String)attributes.get("notificationURL");

		if (notificationURL != null) {
			setNotificationURL(notificationURL);
		}
	}

	@JSON
	@Override
	public long getNotificationConfigId() {
		return _notificationConfigId;
	}

	@Override
	public void setNotificationConfigId(long notificationConfigId) {
		_notificationConfigId = notificationConfigId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEventPattern() {
		if (_eventPattern == null) {
			return StringPool.BLANK;
		}
		else {
			return _eventPattern;
		}
	}

	@Override
	public void setEventPattern(String eventPattern) {
		_eventPattern = eventPattern;
	}

	@JSON
	@Override
	public String getNotificationURL() {
		if (_notificationURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _notificationURL;
		}
	}

	@Override
	public void setNotificationURL(String notificationURL) {
		_notificationURL = notificationURL;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			NotificationConfig.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationConfig toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (NotificationConfig)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationConfigImpl notificationConfigImpl = new NotificationConfigImpl();

		notificationConfigImpl.setNotificationConfigId(getNotificationConfigId());
		notificationConfigImpl.setCompanyId(getCompanyId());
		notificationConfigImpl.setGroupId(getGroupId());
		notificationConfigImpl.setUserId(getUserId());
		notificationConfigImpl.setCreateDate(getCreateDate());
		notificationConfigImpl.setModifiedDate(getModifiedDate());
		notificationConfigImpl.setEventPattern(getEventPattern());
		notificationConfigImpl.setNotificationURL(getNotificationURL());

		notificationConfigImpl.resetOriginalValues();

		return notificationConfigImpl;
	}

	@Override
	public int compareTo(NotificationConfig notificationConfig) {
		long primaryKey = notificationConfig.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NotificationConfig)) {
			return false;
		}

		NotificationConfig notificationConfig = (NotificationConfig)obj;

		long primaryKey = notificationConfig.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<NotificationConfig> toCacheModel() {
		NotificationConfigCacheModel notificationConfigCacheModel = new NotificationConfigCacheModel();

		notificationConfigCacheModel.notificationConfigId = getNotificationConfigId();

		notificationConfigCacheModel.companyId = getCompanyId();

		notificationConfigCacheModel.groupId = getGroupId();

		notificationConfigCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationConfigCacheModel.createDate = createDate.getTime();
		}
		else {
			notificationConfigCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationConfigCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			notificationConfigCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		notificationConfigCacheModel.eventPattern = getEventPattern();

		String eventPattern = notificationConfigCacheModel.eventPattern;

		if ((eventPattern != null) && (eventPattern.length() == 0)) {
			notificationConfigCacheModel.eventPattern = null;
		}

		notificationConfigCacheModel.notificationURL = getNotificationURL();

		String notificationURL = notificationConfigCacheModel.notificationURL;

		if ((notificationURL != null) && (notificationURL.length() == 0)) {
			notificationConfigCacheModel.notificationURL = null;
		}

		return notificationConfigCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{notificationConfigId=");
		sb.append(getNotificationConfigId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", eventPattern=");
		sb.append(getEventPattern());
		sb.append(", notificationURL=");
		sb.append(getNotificationURL());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.opencps.notificationmgt.model.NotificationConfig");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>notificationConfigId</column-name><column-value><![CDATA[");
		sb.append(getNotificationConfigId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventPattern</column-name><column-value><![CDATA[");
		sb.append(getEventPattern());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>notificationURL</column-name><column-value><![CDATA[");
		sb.append(getNotificationURL());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = NotificationConfig.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			NotificationConfig.class
		};
	private long _notificationConfigId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _eventPattern;
	private String _notificationURL;
	private NotificationConfig _escapedModel;
}