/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.duongthuy.tichhop.api.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MessageFunctionData service. Represents a row in the &quot;duongthuy_message_packages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataImpl}.
 * </p>
 *
 * @author binhth
 * @see MessageFunctionData
 * @see org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataImpl
 * @see org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataModelImpl
 * @generated
 */
public interface MessageFunctionDataModel extends BaseModel<MessageFunctionData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a message function data model instance should use the {@link MessageFunctionData} interface instead.
	 */

	/**
	 * Returns the primary key of this message function data.
	 *
	 * @return the primary key of this message function data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this message function data.
	 *
	 * @param primaryKey the primary key of this message function data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message packages ID of this message function data.
	 *
	 * @return the message packages ID of this message function data
	 */
	public long getMessagePackagesId();

	/**
	 * Sets the message packages ID of this message function data.
	 *
	 * @param messagePackagesId the message packages ID of this message function data
	 */
	public void setMessagePackagesId(long messagePackagesId);

	/**
	 * Returns the user ID of this message function data.
	 *
	 * @return the user ID of this message function data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this message function data.
	 *
	 * @param userId the user ID of this message function data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this message function data.
	 *
	 * @return the user uuid of this message function data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this message function data.
	 *
	 * @param userUuid the user uuid of this message function data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this message function data.
	 *
	 * @return the user name of this message function data
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this message function data.
	 *
	 * @param userName the user name of this message function data
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this message function data.
	 *
	 * @return the create date of this message function data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this message function data.
	 *
	 * @param createDate the create date of this message function data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this message function data.
	 *
	 * @return the modified date of this message function data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this message function data.
	 *
	 * @param modifiedDate the modified date of this message function data
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the message function of this message function data.
	 *
	 * @return the message function of this message function data
	 */
	@AutoEscape
	public String getMessageFunction();

	/**
	 * Sets the message function of this message function data.
	 *
	 * @param messageFunction the message function of this message function data
	 */
	public void setMessageFunction(String messageFunction);

	/**
	 * Returns the message ID of this message function data.
	 *
	 * @return the message ID of this message function data
	 */
	@AutoEscape
	public String getMessageId();

	/**
	 * Sets the message ID of this message function data.
	 *
	 * @param messageId the message ID of this message function data
	 */
	public void setMessageId(String messageId);

	/**
	 * Returns the message file ID data of this message function data.
	 *
	 * @return the message file ID data of this message function data
	 */
	public long getMessageFileIdData();

	/**
	 * Sets the message file ID data of this message function data.
	 *
	 * @param messageFileIdData the message file ID data of this message function data
	 */
	public void setMessageFileIdData(long messageFileIdData);

	/**
	 * Returns the send date of this message function data.
	 *
	 * @return the send date of this message function data
	 */
	public Date getSendDate();

	/**
	 * Sets the send date of this message function data.
	 *
	 * @param sendDate the send date of this message function data
	 */
	public void setSendDate(Date sendDate);

	/**
	 * Returns the version of this message function data.
	 *
	 * @return the version of this message function data
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this message function data.
	 *
	 * @param version the version of this message function data
	 */
	public void setVersion(String version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.duongthuy.tichhop.api.dao.model.MessageFunctionData messageFunctionData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.duongthuy.tichhop.api.dao.model.MessageFunctionData> toCacheModel();

	@Override
	public org.duongthuy.tichhop.api.dao.model.MessageFunctionData toEscapedModel();

	@Override
	public org.duongthuy.tichhop.api.dao.model.MessageFunctionData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}