/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.duongthuy.tichhop.api.dao.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import org.duongthuy.tichhop.api.dao.model.MessageFunctionData;
import org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalService;
import org.duongthuy.tichhop.api.dao.service.persistence.MessageFunctionDataPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the message function data local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.duongthuy.tichhop.api.dao.service.impl.MessageFunctionDataLocalServiceImpl}.
 * </p>
 *
 * @author binhth
 * @see org.duongthuy.tichhop.api.dao.service.impl.MessageFunctionDataLocalServiceImpl
 * @see org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalServiceUtil
 * @generated
 */
public abstract class MessageFunctionDataLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MessageFunctionDataLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalServiceUtil} to access the message function data local service.
	 */

	/**
	 * Adds the message function data to the database. Also notifies the appropriate model listeners.
	 *
	 * @param messageFunctionData the message function data
	 * @return the message function data that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MessageFunctionData addMessageFunctionData(
		MessageFunctionData messageFunctionData) throws SystemException {
		messageFunctionData.setNew(true);

		return messageFunctionDataPersistence.update(messageFunctionData);
	}

	/**
	 * Creates a new message function data with the primary key. Does not add the message function data to the database.
	 *
	 * @param messagePackagesId the primary key for the new message function data
	 * @return the new message function data
	 */
	@Override
	public MessageFunctionData createMessageFunctionData(long messagePackagesId) {
		return messageFunctionDataPersistence.create(messagePackagesId);
	}

	/**
	 * Deletes the message function data with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param messagePackagesId the primary key of the message function data
	 * @return the message function data that was removed
	 * @throws PortalException if a message function data with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MessageFunctionData deleteMessageFunctionData(long messagePackagesId)
		throws PortalException, SystemException {
		return messageFunctionDataPersistence.remove(messagePackagesId);
	}

	/**
	 * Deletes the message function data from the database. Also notifies the appropriate model listeners.
	 *
	 * @param messageFunctionData the message function data
	 * @return the message function data that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MessageFunctionData deleteMessageFunctionData(
		MessageFunctionData messageFunctionData) throws SystemException {
		return messageFunctionDataPersistence.remove(messageFunctionData);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MessageFunctionData.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return messageFunctionDataPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return messageFunctionDataPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return messageFunctionDataPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return messageFunctionDataPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return messageFunctionDataPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MessageFunctionData fetchMessageFunctionData(long messagePackagesId)
		throws SystemException {
		return messageFunctionDataPersistence.fetchByPrimaryKey(messagePackagesId);
	}

	/**
	 * Returns the message function data with the primary key.
	 *
	 * @param messagePackagesId the primary key of the message function data
	 * @return the message function data
	 * @throws PortalException if a message function data with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public MessageFunctionData getMessageFunctionData(long messagePackagesId)
		throws PortalException, SystemException {
		return messageFunctionDataPersistence.findByPrimaryKey(messagePackagesId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return messageFunctionDataPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the message function datas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.duongthuy.tichhop.api.dao.model.impl.MessageFunctionDataModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of message function datas
	 * @param end the upper bound of the range of message function datas (not inclusive)
	 * @return the range of message function datas
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<MessageFunctionData> getMessageFunctionDatas(int start, int end)
		throws SystemException {
		return messageFunctionDataPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of message function datas.
	 *
	 * @return the number of message function datas
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getMessageFunctionDatasCount() throws SystemException {
		return messageFunctionDataPersistence.countAll();
	}

	/**
	 * Updates the message function data in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param messageFunctionData the message function data
	 * @return the message function data that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MessageFunctionData updateMessageFunctionData(
		MessageFunctionData messageFunctionData) throws SystemException {
		return messageFunctionDataPersistence.update(messageFunctionData);
	}

	/**
	 * Returns the message function data local service.
	 *
	 * @return the message function data local service
	 */
	public org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalService getMessageFunctionDataLocalService() {
		return messageFunctionDataLocalService;
	}

	/**
	 * Sets the message function data local service.
	 *
	 * @param messageFunctionDataLocalService the message function data local service
	 */
	public void setMessageFunctionDataLocalService(
		org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalService messageFunctionDataLocalService) {
		this.messageFunctionDataLocalService = messageFunctionDataLocalService;
	}

	/**
	 * Returns the message function data persistence.
	 *
	 * @return the message function data persistence
	 */
	public MessageFunctionDataPersistence getMessageFunctionDataPersistence() {
		return messageFunctionDataPersistence;
	}

	/**
	 * Sets the message function data persistence.
	 *
	 * @param messageFunctionDataPersistence the message function data persistence
	 */
	public void setMessageFunctionDataPersistence(
		MessageFunctionDataPersistence messageFunctionDataPersistence) {
		this.messageFunctionDataPersistence = messageFunctionDataPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("org.duongthuy.tichhop.api.dao.model.MessageFunctionData",
			messageFunctionDataLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.duongthuy.tichhop.api.dao.model.MessageFunctionData");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return MessageFunctionData.class;
	}

	protected String getModelClassName() {
		return MessageFunctionData.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = messageFunctionDataPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalService.class)
	protected org.duongthuy.tichhop.api.dao.service.MessageFunctionDataLocalService messageFunctionDataLocalService;
	@BeanReference(type = MessageFunctionDataPersistence.class)
	protected MessageFunctionDataPersistence messageFunctionDataPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private MessageFunctionDataLocalServiceClpInvoker _clpInvoker = new MessageFunctionDataLocalServiceClpInvoker();
}